### ISSUE TITLE
Active Adventure breaks when fighting an enemy.

### ISSUE THREAD

**Issue by Aramythia** [Gelbpunkt/IdleRPG#197] opened 2019-08-29 22:14 UTC
**Describe the bug**
Clicking on the emotes gets no response when attempting to move onto an enemy's tile. The adventure freezes and you can't make any other move.

**To Reproduce**
1. Find a cell with an enemy in it
2. Try going in the direction of that cell

**Comment by Gelbpunkt** [comment] 2019-08-30 04:37
Cannot reproduce

**Comment by Gelbpunkt** [comment] 2019-09-08 08:45
No information provided, closing

**Closed by Gelbpunkt** 2019-09-08 08:45 UTC
Labels: bug, question
