### ISSUE TITLE
Item disappearing after $merchall

### ISSUE THREAD

**Issue by MizukiKurayami** [Gelbpunkt/IdleRPG#316] opened 2019-10-01 00:28 UTC
**Describe the bug**
I did merchall for the first time today, and I had a level 32 sword equipped. Sometime after I did the merchall, I looked at my profile to see how much money I had, and it showed that me sword was gone.

**To Reproduce**
1. Enter command =merchall
2. Hit reaction "Merched 10 items for $1579."

**Expected behavior**
Just sell all the equipment that I did not have equipped

**Screenshots**
See attachements
![Capture](https://user-images.githubusercontent.com/56007382/65925939-a3e13600-e3a7-11e9-82b8-d7adce96d654.PNG)
![unknown (1)](https://user-images.githubusercontent.com/56007382/65925940-a3e13600-e3a7-11e9-9a26-9d56151d7dcf.png)
![unknown](https://user-images.githubusercontent.com/56007382/65925941-a3e13600-e3a7-11e9-8a48-a8400ecf580f.png)

**Desktop (please complete the following information):**
 - Browser: chrome/bluestacks

**Comment by Gelbpunkt** [comment] 2019-10-01 12:35
Cannot reproduce this. The code looks okay

**Comment by Gelbpunkt** [comment] 2019-10-24 19:08
No further info, code is fine. Closing this now. If you want to revive this, please comment below with more information.

**Closed by Gelbpunkt** 2019-10-24 19:08 UTC
