### ISSUE TITLE
Activeadventure.

### ISSUE THREAD

**Issue by forceeeee** [Gelbpunkt/IdleRPG#254] opened 2019-09-14 06:22 UTC
**Describe the bug**
I haven't experienced this bug but so many people complained about it in support and it still hasn't been fixed, the bug is when you do an active adventure, and you encounter an enemy, the 
adventure just stops. There has been too many complaints about it for it to not be fixed.

**To Reproduce**

1. Start the active adventure

2. Encounter an enemy

3. Active adventure stops

4. I get alot of complaints on support

5.I make a github bug post about it

**Comment by maxx0911** [comment] 2019-09-14 06:37
Someone already opened this issue, see [here](https://github.com/Gelbpunkt/IdleRPG/issues/249).

**Comment by Gelbpunkt** [comment] 2019-09-14 07:01
Duplicate of #249

**Closed by Gelbpunkt** 2019-09-14 07:01 UTC
