### ISSUE TITLE
Merchall Limitation

### ISSUE THREAD

**Issue by maxx0911** [Gelbpunkt/IdleRPG#325] opened 2019-10-05 12:12 UTC
**Is your feature request related to a problem? Please describe.**
Some users suggested a way to make `$merchall` be able to sell less items, instead of all of them.

**Describe the solution you'd like**
A system similar to the current `$inventory minstat maxstat` system, where you could use `$merchall 15 25` and all items with stats 15 through 25 (excluding equipped) will be sold, while all other items will be kept in inventory.

**Describe alternatives you've considered**
A system to reserve, favourite, or star items. Starred items can not be sold, neither in `$merch` (would give a warning), nor in `$merchall`. This would require a new column in the inventory table and we would have to rework `$inventory` to show starred items, so I prefer the first idea.

**Additional context**
If you approve of this, I'm ready to write some code, but one thing I do want to ask you is to be able to test it on the beta bot, before releasing it to the public bot. Although I will be testing the database queries this time around, I can't guarantee that my code tests include every possible scenario, so I'd like to test it in action, to make sure I won't be responsible for all items being deleted.

**Comment by maxx0911** [comment] 2019-10-05 12:14
Thank you botto :D

**Comment by Gelbpunkt** [comment] 2019-10-05 18:34
Duplicate of #286

**Closed by Gelbpunkt** 2019-10-05 18:34 UTC
Labels: Priority: Low, enhancement
