### ISSUE TITLE
Exchange All / Sacrifice All - Command for Loot

### ISSUE THREAD

**Issue by ArtCRaVe** [Gelbpunkt/IdleRPG#237] opened 2019-09-09 03:36 UTC
**Is your feature request related to a problem? Please describe.**
People who like to hoard loot or playing on the phone or whilst at work when the time usage is crucial, especially the ones who play on phone, you cant even copy paste the image not to mention there's a 1min cooldown in between exchange, you also cant do multiple at once.

**Describe the solution you'd like**
An $exchange all and $sacrifice all command would be nice, perhaps similar to $merchall command for inventory.

**Describe alternatives you've considered**
If not, removing the cooldown and being able to just copy the **$exchange itemID and $sacrifice itemID** for phone/mobile use would be great as well. Being able to do multiple loot at once also works, basically all in all similar to how you manage inventory.

Thank you ~

**Comment by Gelbpunkt** [comment] 2019-09-09 05:27
Duplicate of #223

**Closed by Gelbpunkt** 2019-09-09 05:27 UTC
