### ISSUE TITLE
Make child by urself

### ISSUE THREAD

**Issue by Quinemaniac** [Gelbpunkt/IdleRPG#203] opened 2019-08-30 12:36 UTC
**Describe the bug**
U can fuck urself to make child when u married to someone but they arent in the server that u do command $fuck

**To Reproduce**
1. Do '$fuck' in the server they arent in
2. Hit reaction ✅
3. and enjoy the result

**Screenshots**
Forgot to take them but i tested

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SMar7-Fox** [comment] 2019-08-30 12:38
Tested too, worked.

**Comment by numbermaniac** [comment] 2019-08-30 14:02
I assume the issue is because of these two lines:

https://github.com/Gelbpunkt/IdleRPG/blob/v4/cogs/marriage.py#L326
https://github.com/Gelbpunkt/IdleRPG/blob/v4/classes/context.py#L39

If the user can't be found by the bot, `get_user` will return None, and then `ctx.confirm` interprets `None` as the author of the message - allowing the author to select the check mark reaction.

**Comment by Gelbpunkt** [comment] 2019-08-31 18:28
Fixed in v4.1

**Closed by Gelbpunkt** 2019-08-31 18:28 UTC
