### ISSUE TITLE
Crate merging

### ISSUE THREAD

**Issue by mrfluffykins** [Gelbpunkt/IdleRPG#168] opened 2019-08-25 19:56 UTC
The ability to merge lower tier rarity crates into higher tiers,
For example 50 common crates would merge into 1 uncommon and 45 uncommon crates would be able to merge into 1 rare, etc.etc.etc.

**Comment by Gelbpunkt** [comment] 2019-08-25 19:58
Duplicate of #157

**Closed by Gelbpunkt** 2019-08-25 19:58 UTC
